# Generated by Django 4.1.3 on 2022-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_interfaces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='接口id')),
                ('service_name', models.CharField(max_length=50, verbose_name='服务名')),
                ('interface_name', models.CharField(max_length=300, verbose_name='接口url')),
                ('interface_mock_id', models.CharField(default=0, max_length=20, verbose_name='接口mock数据，为0为随机mock')),
                ('is_delete', models.SmallIntegerField(default=0, verbose_name='是否删除:0-正常；1-删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'mcok_interfaces',
            },
        ),
        migrations.CreateModel(
            name='Mock_lists',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='mockid')),
                ('mock_name', models.CharField(max_length=30, verbose_name='mock名称')),
                ('mock_data', models.CharField(max_length=3000, verbose_name='mock数据')),
                ('mock_interface_id', models.CharField(max_length=50, verbose_name='mock接口id')),
                ('is_delete', models.SmallIntegerField(default=0, verbose_name='是否删除:0-正常；1-删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'mcok_lists',
            },
        ),
    ]
